feat: add faq components and section on signup page
privacy-scaling-explorations/maci-rpgf pull request #190
Opened 2024-06-28 16:44 UTC by kittybest

**Description**
- add FAQ section on the signup page
- this is just an FAQ template, who fork this branch should modify the `FAQList` part.

2024-06-28 16:55 UTC, ctrlc03 commented on src/features/signup/components/faqList.tsx
> +      description="This found is focused on supporting Mexican projects working on reducing the gender gap, collaborating with local communities, and ReFi."
typo: "round"

2024-06-28 16:56 UTC, ctrlc03 commented on src/features/signup/components/faqList.tsx
> +      description="This found is focused on supporting Mexican projects working on reducing the gender gap, collaborating with local communities, and ReFi."
Let's remove mentions to EthMexico? "This round is focused on supporting public goods projects which made an impact on the Ethereum ecosystem" (to be more general)

2024-06-28 16:56 UTC, ctrlc03 commented on src/features/signup/components/faqList.tsx
> +            This round will be enabled by EasyRetroPGF Hypercerts EAS and MACI, Minimal Anti-Collusion Infrastructure.
there's no hypercerts

2024-06-28 16:57 UTC, ctrlc03 commented on src/features/signup/components/faqList.tsx
> +            This round will be enabled by EasyRetroPGF Hypercerts EAS and MACI, Minimal Anti-Collusion Infrastructure.
Minimal Anti-Collusion Infrastructure (MACI)

2024-06-28 16:58 UTC, ctrlc03 commented on src/features/signup/components/faqList.tsx
> +      description="To participate in this round as a project or as a voter, you must be a Mexican community member and have on-chain proofs, such as: POAPs, Unlock Protocol, NFTs or EAS."
you must be whitelisted by the organizers and old either a specific NFT, POAP or an EAS attestation

2024-06-28 17:00 UTC, 0xmad requested changes
@kittybest thanks, left some comments

2024-06-28 17:00 UTC, 0xmad commented on playwright-report/index.html
This folder should not be commited

2024-06-28 17:00 UTC, 0xmad commented on src/features/signup/components/faqItem.tsx
> +          alt=""
Please add alt

2024-06-28 17:00 UTC, 0xmad commented on src/layouts/BaseLayout.tsx
> +  paddingX = true,
Passing style props is not a good practice. Use class name instead

2024-06-28 17:00 UTC, 0xmad commented on src/layouts/DefaultLayout.tsx
> +type ILayoutProps = PropsWithChildren<
Let's use interface instead

2024-06-28 17:04 UTC, kittybest commented on playwright-report/index.html
yes I just found, thanks for reminding

2024-07-01 13:57 UTC, 0xmad commented on src/features/signup/components/faqItem.tsx
File name should be FaqItem

2024-07-01 13:57 UTC, 0xmad commented on src/features/signup/components/faqList.tsx
File name should be FaqList

2024-07-01 16:29 UTC, kittybest commented on src/features/signup/components/faqItem.tsx
I renamed it, but it became to be duplicate files, let me figure it out

2024-07-01 16:34 UTC, 0xmad approved these changes
@kittybest thanks!

2024-07-01 16:41 UTC, merged